server:
  port: 8082
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/housing-utilities
    username: maksim
    password: 16111999maksim
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
security:
  oauth2:
    client:
      clientId: exampleClient
      clientSecret: exampleSecret
      accessTokenUri: http://localhost:8090/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
