server:
  port: 8091
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:${EUREKA_SERVER_URL}/eureka}
  instance:
    preferIpAddress: true
spring:
  cloud:
    stream:
      kafka:
        binder:
          brokers: ${KAFKA_URL}
      bindings:
        electricity-service:
          destination: housing-utilities-electricity-service
          content-type: application/json
        water-service:
          destination: housing-utilities-water-service
          content-type: application/json
        water-disposal:
          destination: housing-utilities-water-disposal
          content-type: application/json
        maintenance-service:
          destination: housing-utilities-maintenance-service
          content-type: application/json
        elevator-maintenance:
          destination: housing-utilities-elevator-maintenance
          content-type: application/json
        overhaul-service:
          destination: housing-utilities-overhaul-service
          content-type: application/json

