server:
  port: 8090
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:${EUREKA_SERVER_URL}/eureka}
  instance:
    preferIpAddress: true
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://${DB_URL}/housing_utilities
    username: root
    password: 16111999m
    initialization-mode: always
  jpa:
    hibernate:
      ddl-auto: update
refresh:
  token:
    validity:
      seconds: 2_592_000
access:
  token:
    validity:
      seconds: 18_000
login:
  external:
    url: http://localhost:3000/home
