server:
  port: 8085
eureka:
  client:
    serviceUrl:
      defaultZone: ${EUREKA_URI:http://localhost:8761/eureka}
  instance:
    preferIpAddress: true
security:
  oauth2:
    client:
      clientId: exampleClient
      clientSecret: exampleSecret
      accessTokenUri: http://localhost:8090/oauth/token
      grant-type: client_credentials
      scope: server
    resource:
      token-info-uri: http://localhost:8090/oauth/check_token
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/housing_utilities_water_disposal
    username: root
    password: 16111999m
  jpa:
    hibernate:
      ddl-auto: update
  cloud:
    stream:
      kafka:
        binder:
          brokers: localhost:9092
      bindings:
        input:
          destination: housing-utilities-water-disposal
          content-type: application/json
count:
  of:
    months: 12
price:
  per:
    cubic:
      meter: 0.5518
