server:
  port: 8082
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/housing-utilities
    username: maksim
    password: 16111999maksim
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
